gdcSite/gdcSite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'wiki/',include('wiki.urls',namespace="wiki-page")),
    path(r'',include('home.urls', namespace="home-page")),
]

gdcSite/home/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib import admin
from . import views

app_name="home"
urlpatterns = [
        url(r'contacts',views.contact,name='contact'),
        url(r'directions',views.directions,name='directions'),
		  url(r'projects',views.project,name='project'),
		  path(r'apply',views.apply,name='apply'),
		  url(r'showcase',views.showcase,name='showcase'),
		  url(r'ppHowTo',views.PPHowTo,name='pphowto'),
		  url(r'unitytutorialprep',views.UnityTutorial,name="unitytut"),
		  path(r'admin',admin.site.urls),
		  path(r'usefulLinks',views.usefulLinks,name="links"),
		  url(r'',views.index,name="index"),
]

gdcSite/wiki/urls.py
from django.conf.urls import url
from . import views

app_name="wiki"
urlpatterns= [
      url(r'^(?P<member_id>[0-9]+)/$',views.member, name="member"),  
		url(r'^$',views.wiki, name="index"),
        ]

gdcSite/home/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

gdcSite/wiki/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Skill(models.Model):
    skill_Name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.skill_Name

class ClubMember(models.Model):
    name = models.CharField(max_length=50)
    skills = models.ManyToManyField(Skill)
    discord = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    
    def __str__(self):
        return  self.name


    

gdcSite/home/views.py
from django.shortcuts import render, redirect
from django.template import Context, loader
from django.template.loader import render_to_string
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.core.mail import send_mail

# Create your views here.
def index(request):
    template = loader.get_template("home/index.html")
    return HttpResponse(template.render())

def newindex(request):
    template = loader.get_template("home/newindex.html")
    return HttpResponse(template.render())

def contact(request):
    template = loader.get_template("home/contacts.html")
    return HttpResponse(template.render())

def directions(request):
    template = loader.get_template("home/directions.html")
    return HttpResponse(template.render())

def project(request):
	referer = request.META.get('HTTP_REFERER')
	if referer:
		if "apply" in referer:
			return render(request,"home/project.html",{'error_message':"Success",})
	return render(request,"home/project.html")

def apply(request):
	try:
		name = request.POST['Name']
		watiam = request.POST['Watiam']
		gitlabUserName = request.POST['GLUserName']
		if name == "" or watiam == "" or gitlabUserName=="":
			raise Exception("Name is not defined")
	except:
		return render(request,'home/project.html',{'error_message':"Form not filled out fully",})
	else:
		message = name + " would like to join the Pocket Pirates development team.<br>Watiam: " + watiam + "<br>Gitlab Username: " + gitlabUserName
		send_mail("Pocket Pirates New Application","","uw.gamedevclub.website@gmail.com",["uw.gamedevclub@gmail.com"],html_message=message)
		return redirect('home:project')

def showcase(request):
	return render(request,"home/showcase.html")

def PPHowTo(request):
	return render(request,"home/pphowto.html")

def UnityTutorial(request):
	return render(request,"home/unitytut.html")

def usefulLinks(request):
	return render(request,"home/usefullinks.html") 

gdcSite/wiki/views.py
from django.template import loader, Context
from django.shortcuts import render
from django.http import HttpResponse, Http404
from .models import ClubMember, Skill
# Create your views here.

def wiki(request):
	memberList = ClubMember.objects.order_by('name')
	skillList = Skill.objects.order_by('skill_Name')
	context = {'memberList': memberList,'skillList':skillList }
	template = loader.get_template("wiki/wiki.html")
	return render(request,'wiki/wiki.html',context)

def member(request,member_id):
	try:
		member = ClubMember.objects.get(pk=member_id)
	except ClubMember.DoesNotExist:
		raise Http404("Member does not exist")
	return render(request,'wiki/member.html',{'member':member})

gdcSite/home/templates/home/contacts.html
<html>
	<head>
		<meta charset="UTF-8">
	       	<title>University of Waterloo Game Dev Club </title>
		{% include 'home/headTemplate.html' %}	
	</head>
	<body>
		{% include 'home/navbar.html' %}
		<div class="container-fluid">
			<div class="row" style="min-height:100%">
				{% include 'home/verticalNav.html' %}
				<div class="col-12 col-sm-8 col-md-8 col-lg-9 col-xl-9">
					<h1> Contact Us</h1>
						<div>
							<h4><a href="https://discord.gg/z7XMSPt">Discord</a></h4>
							<p>Join our discord for discussion with other club members and information on upcoming talks/events. Feel free to message our execs here or post any questions or suggestions in the appropriate channels</p>
						</div>
						<div>
							<h4><a href="https://www.facebook.com/groups/298486077021523/">Facebook</a></h4>
							<p>
								Stay up do date on club information through our facebook group
							</p>
						</div>
						<div>
							<h4><a href="mailto:uw.gamedevclub@gmail.com">Email</a></h4>
							<p>If you have any questions or concerns you'd like to send to our executives, you can reach them at our club email above.</p>


						</div>	
				</div>
			</div>
		</div>	
	</body>
</html>

gdcSite/home/templates/home/directions.html
{% load static %}
<html>
	<head>
		<meta charset="UTF-8">
		<title>University of Waterloo Game Dev Club</title>
		{% include 'home/headTemplate.html' %}
	</head>
	<body>
		{% include 'home/navbar.html' %}
		<div class="container-fluid">
			<div class="row" style="min-height:100%">
				{% include 'home/verticalNav.html' %}
				<div class="col-12 col-sm-8 col-md-8 col-lg-9 col-xl-9">
				<h1> Direction To Meetings</h1>	
				<p>Looking to join us at the Games Institute? Great! Follow these instructions to find it in East Campus 1.</p>
				<p>EC1 is listed on the campus map in the extreme upper right edge of campus</p>
				<img src="{% static 'home/campus.png' %}">
				<p>You're looking for the door right here (as show from Google satellite view</p>
				<div id="map">
					<img frameborder="0" style="border:0" src="https://www.google.com/maps/api/staticmap?center=43.475869,-80.539864&zoom=18&size=200x200&maptype=satellite&markers=size:tiny:|color:blue|label:A|43.475869,-80.539864&key=AIzaSyAtl6kdNYkkS5hyDH7iQfi92IA2NGifS08" allowfullscreen>
				</div>	
				<p>If you're still a bit confused how to get there, try to follow these steps. Or, contact us at <a href="mailto:uw.gamedevclub@gmail.com">uw.gamedevclub@gmail.com</a></p>
				<ol>
				<li>
					<p>Start outside DC facing the bus stops</p>
					<img src="{% static 'home/step1.jpg' %}">
				</li>
				<li>
					<p>Head to the left and pass over the train tracks</p>
					<img src="{% static 'home/step2.jpg' %}">
				</li>
				<li>
					<p>Find the building closest to the two major roads to the north and east of you. It's going to look like this</p>
					<img src="{% static 'home/step3.jpg' %}">
				</li>
				<li>
					<p>Enter via the ominous door</p>
					<img src="{% static 'home/step4.jpg' %}">
				</li>
				<li>
					<p>Have fun!</p>
				</li>
				</ol>
			</div>
		</div>
	</body>
	<script>
		function initMap(){
			var uluru = 

</html>

gdcSite/home/templates/home/headTemplate.html
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, target-densityDpi=device-dpi">
	<link rel="stylesheet" type="text/css" href="{% static 'home/bootstrap.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'home/navbar.css' %}"/>
	
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
	<script src="{% static 'home/bootstrap.js' %}"></script>

gdcSite/home/templates/home/index.html
{% load static %}
<html>
<head>
	<meta charset="UTF-8">
	<title>University of Waterloo Game Dev Club</title>
	{% include 'home/headTemplate.html' %}
</head>
<body>
	{% include 'home/navbar.html' %}
	<div class="container-fluid">
	<div class="row" style="min-height:100%">
		{% include 'home/verticalNav.html' %}
		<div class="col-12 col-sm-8 col-md-8 col-lg-9 col-xl-9">
		<h1> Learn. Create. Explore.</h1>
		<p class="lead">
		Join our community of game developers - from artists, to designers, to play testers - Thursdays at 6pm in the GI Collaboration Space. We hold tutorials, play and discuss games, and hold other events on video, board, card, and role-playing games. No previous game dev experience required.

		We also have space (and players) if you want to play test your own game. You can also participate in one of the club's projects, learn how to start your own, or just kick back after classes with other game lovers.
		</p>
		<div>
			<h4>LEARN Event 2018</h4>
			<p class="lead">The LEARN event is a free to attend series of talks and tutorials on game making and game desgin, no prior experience required. The LEARN event takes place on January 20th and 21st in QNC 2502 starting at 9am both days and is free to attend. For details on which talks are happening at what time, reference the calender below.</p>
			<p class="lead">If you are planning to participate in the Blender, Unity or Unreal tutorials please download the software prior to attending. Download links can be found here:</p>
			<ul>
				<li><p><a href="https://www.blender.org">Blender</a></p></li>
				<li><p><a href="https://unity3d.com">Unity</a></p></li>
				<li><p><a href="https://www.unrealengine.com/en-US/what-is-unreal-engine-4">Unreal Engine</a></p></li>
			</ul>
		</div>
		<div>
			<h4>
				Sign Up For Our Mailing List
			</h4>
				<form action="//uwaterloo.us11.list-manage.com/subscribe/post?u=f939182d04c769c076b58a84b&amp;id=2335dd7531" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" novalidate>
    <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" placeholder="e-mail address" autocomplete="off"/>
    <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button" />
</form>
			
		</div>
		<div class="d-none d-sm-block">
		<iframe src="https://calendar.google.com/calendar/embed?src=80ar36dhg37vskmhd4gjb2els4%40group.calendar.google.com&ctz=America%2FToronto" style="border: solid 1px #777" width="80%" height="600" frameborder="0" scrolling="no"></iframe>
		</div>
		<div class="d-sm-none">
		<iframe src="https://calendar.google.com/calendar/embed?src=80ar36dhg37vskmhd4gjb2els4%40group.calendar.google.com&ctz=America%2FToronto&amp;mode=AGENDA" style="border: solid 1px #777" width="100%" height="600" frameborder="0" scrolling="no"></iframe>
		</div>
		</div>
	</div>
	</div>
</body>

</html>

gdcSite/home/templates/home/navbar.html
	<nav class="navbar navbar-expand-md navbar-dark bg-dark">
		<div class="container-fluid">
			<a class="navbar-brand mr-auto" href="{% url 'home:index' %}"><h2 data-toc-skip class="club-name-sub">University of Waterloo</h2><h1 data-toc-skip class="club-name">Game Development Club</h1></a>
		<ul class="navbar-nav ml-auto">
			<li>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMobile" aria-controls="navbarMobile" aria-expanded="false" aria-lable="Toggle navigation"><span class="navbar-toggler-icon"></span>
				</button>
			</li>
		</ul>
		</div>
	</nav>
	<div class="collapse" id="navbarMobile">
		<ul class="navbar-nav bg-dark mr-auto">
			<li class="nav-item active">
				<a class="nav-link" href="{% url 'home:index' %}">Home</a>
				<a class="nav-link" href="{% url 'home:contact' %}">Contact Us</a>
				<a class="nav-link" href="{% url 'home:directions' %}">Directions</a>
				<a class="nav-link" href="{% url 'wiki:index' %}">Skills Wiki</a>
				<a class="nav-link" href="{% url 'home:showcase' %}">Project Showcase</a>
				<a class="nav-link" href="{% url 'home:project' %}">Club Project</a>
				<a class="nav-link" href="{% url 'home:links' %}">Useful Links</a>
			</li>
		</ul>
	</div>

gdcSite/home/templates/home/pphowto.html
{% load static %}
<html>
<head>
	<meta charset="UTF-8">
	<title>University of Waterloo Game Dev Club</title>
	{%	include 'home/headTemplate.html' %}
	<link rel="stylesheet" href="https://cdn.rawgit.com/afeld/bootstrap-toc/v0.4.1/dist/bootstrap-toc.min.css">
	<script src="https://cdn.rawgit.com/afeld/bootstrap-toc/v0.4.1/dist/bootstrap-toc.min.js"></script>
</head>
<body data-spy="scroll" data-target="#toc">
	{% include 'home/navbar.html' %}
	<div class="container-fluid">
	<div class="row" style="min-height:100%">
		{% include 'home/verticalNav.html' %}
		<div class="col-2 col-sm-2 col-md-2 col-lg-2 col-xl-2" id="tocDiv" style="position:sticky;"> 
			<div class="affix">
		
			<nav id="toc" data-toggle="toc"></nav>
			</div>
		</div>
		<div class="col-10 col-sm-6 col-md-6 col-lg-7 col-xl-7">
			<h1 data-toc-skip>Getting Started With Pocket Pirates</h1>
				<p>
					Welcome to the Pocket Pirates project. This guide is to help you get started with working on Pocket Pirates. If you have not already gotten access to the Gitlab repository please send an application <a href="{% url 'home:project' %}"> here</a>.
				</p>
			<h2>Cloning The Pocket Pirates Repository</h2>
				<p>
					This project uses Git for version control, if you do not have a Git utility installed we recommend Sourcetree, which you can download <a href="https://www.sourcetreeapp.com/download-archives">here</a>. If you are new to git entirely we recommend <a href="https://www.atlassian.com/git/tutorials/learn-git-with-bitbucket-cloud">Atlassian's tutorial on Git</a>.
				<ol>
					<li>
						Navigate to the <a href="https://gitlab.com/UniversityOfWaterlooGameDevelopmentClub/PocketPirates">Pocket Pirates Gitlab page</a>.
					</li>
					<li>
						Clone the source url given on the Gitlab page, if using Sourcetree select the destination path as where you want Pocket Pirates to be installed. 
					</li>
					<li>
						Ensure that the Pocket Pirates files are installed in your new git repo.
					</li>
				</ol>
				</p>
			<h2>Opening Pocket Pirates In Unity</h2>
				<p>
					Make sure you have at least Unity 2017.3 installed. If you do not have the latest version installed you can download it <a href="https://store.unity.com/download?ref=personal">here</a>.
				</p>
				<ol>
					<li>
						Open Unity and click "Open" in the top right of the start sceen.
					</li>
					<li>
						Navigate to the directory you installed Pocket Pirates in, the select folder button should appear if it was set up correctly. Click the select folder button.
					</li>
					<li>
						If Unity warns about non-matching editor versions, click continue, it will port the project to the latest verion
					</li>			
					<li>
						Try opening a stable scene and run to make sure everything is loaded correctly
					</li>
			</ol>
			<h2>Working On Pocket Pirates</h2>
				<p>
					Pocket Pirates uses a style guide, so please reference this before making any changes to the project. We also use Git Workflow for Pocket Pirates, if you do not know what Git Workflow is please check <a href="https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow">here</a>.
				</p>
			<h2 id="New-Feature">Working On A New Feature</h3>
				<p>
					Reference these steps if you are starting a new feature for Pocket Pirates
				</p>
				<ol>
					<li>
						Create a new branch, title this branch descriptively (IE: If you are working on implementing a new bomb powerup, for expample, name your branch "BombPowerup"). In SourceTree click the branch button and enter your branch name, leave the other options on their defaults. Then click create branch, you will now be on your new branch.
					</li>
					<li>
						Edit the project with your new changes, remember to commit to your branch whenever you've got new additions stable. To commit in Sourcetree, click the commit button. Begin by staging new files you've added to the project. You can do this by selecting the new file in the unstaged section of the commit screen and clicking stage selected. Next type a commit message in the box at the bottom of the screen. This message should detail exactly what your commit changess. Finally once your commit is ready, press "Commit" in the bottom right.
					</li>
					<li>
						Once you're finished commiting, you should push to your feature branch. To do this in Sourcetree click push. Select the checkbox next to the branch for your feature, and then click Push at the bottom of the dialog.
					</li>
					<li>
						If your feature is finished, see the section "Tying Up Your New Feature" for how to submit a merge request.
					</li>
				</ol>
			<h2 id="Helping-With-Existing-Features">Helping With Existing Features</h3>
				<p>
					Reference this if you are working on a branch that already exists
				</p>
				<ol>
					<li>
						First make sure you fetch all changes to the repo. In Sourcetree do this by clicking fetch.A dialog will show up, leave the options on their defaults and click ok. 
					</li>
					<li>
						Next checkout the branch you would like to work on. To do this in Sourcetree, open the list of branches on the left panel and right click the branch you would like to work on. Click the option checkout branch and click ok.
					</li>
					<li>
						Pull the current branch to get all the changes so far. To do this in Sourcetree click the pull button. If the button has a number beside it, that is the number of commits that are not on your branch. In the pull dialog, make sure the remote branch is set to the branch you want to pull, then click ok.
					</li>
					<li>
						Make changes to the project in Unity, try to coordinate with others not to work on the same files, otherwise a merge will be required. Remember to commit to your branch whenever you've got new additions stable. To commit in Sourcetree, click the commit button. Begin by staging new files you've added to the project. You can do this by selecting the new file in the unstaged section of the commit screen and clicking stage selected. Next type a commit message in the box at the bottom of the screen. This message should detail exactly what your commit changess. Finally once your commit is ready, press "Commit" in the bottom right.
					</li>
					<li>
						Once you're finished commiting, you should push to your feature branch. To do this in Sourcetree click push. Select the checkbox next to the branch for your feature, and then click Push at the bottom of the dialog.
					</li>
					<li>
						If your feature is finished, see the section "Tying Up Your New Feature" for how to submit a merge request.
					</li>
				</ol>
			<h2>Tying Up Your New Feature</h2>
			<p>
				Once your feature is finished and tested, now it is time to make a merge request.
			</p>	
			<ol>
				<li>
					Navigate to the Pocket Pirates Gitlab and click the Merge Requests tab.
				</li>
				<li>
					Click the green button labeled "New merge request"
				</li>
				<li>
					In the Select source branch dropdown, select the branch for your feature, make sure the target branch is master. Once done, click the Compare branches button.
				</li>
				<li>
					In the description type a summary of changes your feature makes. If you think there is anyone in particular you'd like to review your code, select them in the Assignee dropdown. Once finished, click the Submit merge request button.
				</li>
				<li>
					Congratulations! Someone will review your code, and if it functions properly and adheres to standards it will be added to the master branch of Pocket Pirates.
				</li>
			</ol>
		</div>
	</div>
	</div>
</body>
</html>

gdcSite/home/templates/home/project.html
{% load static %}
<html>
<head>
	<meta charset="UTF-8">
	<title>University of Waterloo Game Dev Club</title>
	{% include 'home/headTemplate.html' %}
</head>
<body>
	{% include 'home/navbar.html' %}
	<div class="container-fluid">
	<div class="row" style="min-height:100%">
		{% include 'home/verticalNav.html' %}
		<div class="col-12 col-sm-8 col-md-8 col-lg-9 col-xl-9">
			<h1>
				Club Project
			</h1>
			<p>
			   Our club runs community projects throughout the term that anyone can contribute to. The current projects are Pocket Pirates and The Lower City.
			</p>
			<div>
				<h2>
					Pocket Pirates
				</h2>
				<div>
					<h4>
						About
					</h4>
					<p>
						Pocket Pirates is a 2D top down team space fighter featuring drop-in, drop-out local network play.   
					</p>
				</div>
				<div>
					<h4>
						How To Contribute
					</h4>
					<p>
						To contribute to Pocket Pirates please fill in the application form below. We host Pocket Pirates through GitLab so we require you to have a gitlab account in order to contribute. 
					</p>
					<p>
						Once you have access to the project, instructions on how to contribute to the project can be found <a href="{% url 'home:pphowto' %}"> here </a>
					</p>
					{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
					<form action="{% url 'home:apply' %}" method="post">{% csrf_token %}
						<label for="Name">Full name:</label><br>
						<input type="text" name="Name"/><br>
						<label for="Watiam">Watiam:</label><br>
						<input type="text" name="Watiam"/><br>
						<label for="GLUserName">GitLab Username:</label><br>
						<input type="text" name="GLUserName"/><br>
						<input type="submit" value="Submit"/>
					</form>
				</div>	
			</div>
			<h2>
				The Lower City
			</h2>
			<div>
				<h4>
					About
				</h4>
				<p>
					The Lower City is a table-top role-playing game based off of FATE. It is set in a dystopian future, among the crumbling slums created by the apathy of a larger society.
				</p>
			</div>
			<div>
				<h4>
					How To Contribute
				</h4>
				<p>
					To contribute to The Lower City attend Game Dev Club meetings and ask execs on how you can help.
				</p>
			</div>
		</div>
	</div>
	</div>	
</body>
</html>

gdcSite/home/templates/home/unitytut.html
{% load static %}
<html>
<head>
	<meta charset="UTF-8">
	<title>University of Waterloo Game Dev Club</title>
	{% include 'home/headTemplate.html' %}
</head>
<body>
	{% include 'home/navbar.html' %}
	<div class="container-fluid">
	<div class="row" style="min-height:100%">
		{% include 'home/verticalNav.html' %}
		<div class="col-12 col-sm-8 col-md-8 col-lg-9 col-xl-9">
			<h1>
				Unity UFO Tutorial Prep
			</h1>	
			<p>Below are the preperation steps for the Unity UFO tutorial<p>
			<h4>On Unity Website:</h4>
			<ol>
				<li>Download and install <a href="https://store.unity.com/download?ref=personal">Unity 2017.3</a></li>
				<li>Go to <a href="https://www.assetstore.unity3d.com/en/#!/content/52143">https://www.assetstore.unity3d.com/en/#!/content/52143</a></li>
				<li>Click "Add to downloads"</li>
				<li>Click "Open in Unity"</li>
			</ol>
			<h4>In Unity:</h4>
			<ol start="5">
				<li>
					Click "New" button to create a new project
					<ul>
						<li>Fill in the following information</li>
						<li>Project name: UFO Tutorial</li>
						<li>Location: (Select a place for your project)</li>
						<li>Select 2D</li>
					</ul>
				</li>
				<li>
					Unity will open with Asset Store tab open
					<ul>
						<li>Scroll down and click "Download" (will be "Import" if you have downloaded this package before)</li>
						<li>Click "Accept"</li>
						<li>Click "Import"</li>
						<li>Make sure all checkboxes are checked and click "Import"</li> 
					</ul>
				</li>
				<li>
					In Unity click "File" -&gt;"Save Scene"
					<ul>
						<li>Create a new folder named "Scenes" in the Assets folder (Assets should be the default save directory)</li>
						<li>Save scene with filename "Main"</li>
					</ul>
				</li>
				<li>In Unity click "File" -&gt;"Save Project"</li>
			</ol>
		<p>Now you're ready for the tutorial<p>
		</div>	
	</div>
	</div>
</body>
</html>

gdcSite/home/templates/home/verticalNav.html
<div class="d-none d-sm-block col-sm-3 col-md-3 col-lg-2 col-xl-2 bg-light">
			<ul class="nav flex-column">
				<li class="nav-item">
					<a class="nav-link active" href="{% url 'home:index' %}">Home</a>
					<a class="nav-link" href="{% url 'home:contact' %}">Contact Us</a>
					<a class="nav-link" href="{% url 'home:directions' %}">Directions To Meetings</a>
					<a class="nav-link" href="{% url 'wiki:index' %}">Skills Wiki</a>
					<a class="nav-link" href="{% url 'home:showcase' %}">Project Showcase</a>
					<a class="nav-link" href="{% url 'home:project' %}">Club Project</a>
					<a class="nav-link" href="{% url 'home:links' %}">Useful Links</a>
				</li>
			</ul>
		</div>

gdcSite/wiki/templates/wiki/wiki.html
{% load static %}
<html>
	<head>
		<meta charset="UTF-8">
		<title>University of Waterloo Game Dev Club</title>
		{% include 'home/headTemplate.html' %}
		<script src="{% static 'wiki/sortSwitch.js' %}"></script>
	</head>
	<body>
		{% include 'home/navbar.html' %}
		<div class="container-fluid">
			<div class="row" style="min-height:100%">
				{% include 'home/verticalNav.html' %}
				<div class="col-12 col-sm-8 col-md-8 col-lg-9 col-xl-9">
					<h1>Skills Wiki </h1>
					<p>This is a directory of club members who are willing to help mentor in  skills to people interested</p>
					<form>
					{% if memberList %}
					<label>Sort by:</label>
					<select id="sort" onChange="changeSort()">
						<option value="Members">Members
						</option>
						<option value="Skills">Skills
						</option>
					</select>
					</form>
					{% endif %}
					<div id="memberSort">
					{% if memberList %}
					<ul>
						{% for member in memberList %}
							<li>
								<p>
									<a href="{% url 'wiki:member' member.id %}">{{member.name}}</a>
								<ul>
									{% for skill in member.skills.all %}
									<li>{{skill.skill_Name}}</li>
									{% endfor %}
								</ul>
								</p>
							</li>
						{% endfor %}
					</ul>
					{% else %}
					There are no members volunteering skills mentorship right now
					{% endif %}
					</div>
					<div id="skillSort">
					{% if skillList %}
					<ul>
						{% for skill in skillList %}
						<li>
							<p>{{skill.skill_Name}}
							<ul>
								{% for member in skill.clubmember_set.all %}
								<li><a href="{% url 'wiki:member' member.id %}">{{member.name}}</a></li>
								{% endfor %}
							</ul>
							</p>
						</li>
						{% endfor %}
					</ul>
					{% endif %}
					</div>
				</div>
		</div>
	</body>
</html>